# Generated by Django 3.2.20 on 2024-08-13 11:51

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('creator', models.CharField(max_length=250)),
                ('publisher', models.CharField(max_length=250)),
                ('fontType', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), blank=True, default=list, size=None)),
                ('recordId', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FontType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('height', models.IntegerField()),
                ('mShape', models.CharField(max_length=15)),
                ('alphabetImage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('officeName', models.CharField(max_length=255)),
                ('alternativeName', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('foundedYear', models.IntegerField(blank=True, null=True)),
                ('closedYear', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('creator', 'Creator'), ('printer', 'Printer')], max_length=10)),
                ('fullName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('role', models.IntegerField(choices=[(0, 'Expert'), (1, 'Normal User')])),
            ],
        ),
        migrations.CreateModel(
            name='OfficePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people_association', to='incunabula.office')),
                ('personID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_association', to='incunabula.person')),
            ],
        ),
        migrations.CreateModel(
            name='FontTypeBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='font_types', to='incunabula.book')),
                ('fontTypeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='incunabula.fonttype')),
            ],
        ),
        migrations.AddField(
            model_name='fonttype',
            name='officeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='font_types', to='incunabula.office'),
        ),
        migrations.AddField(
            model_name='book',
            name='printingOffice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='incunabula.office'),
        ),
    ]
