# Generated by Django 3.2.20 on 2024-08-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incunabula', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='id',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
    ]
