# Generated by Django 3.2.20 on 2024-08-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incunabula', '0004_auto_20240813_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
