# Generated by Django 3.2.20 on 2024-08-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incunabula', '0005_alter_book_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
