# Generated by Django 3.2.20 on 2024-08-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incunabula', '0006_alter_book_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fonttype',
            name='alphabetImage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
