# Generated by Django 3.2.20 on 2024-08-20 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incunabula', '0008_remove_book_fonttype'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fonttypebook',
            unique_together={('fontTypeID', 'bookID')},
        ),
        migrations.AlterUniqueTogether(
            name='officeperson',
            unique_together={('officeID', 'personID')},
        ),
    ]
