# Generated by Django 3.2.20 on 2024-08-26 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incunabula', '0010_alter_person_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fonttype',
            name='officeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fontTypes', to='incunabula.office'),
        ),
        migrations.AlterField(
            model_name='fonttypebook',
            name='bookID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fontTypes', to='incunabula.book'),
        ),
    ]
