# Generated by Django 3.2.20 on 2024-09-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incunabula', '0013_auto_20240912_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
