# Generated by Django 3.2.20 on 2024-09-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incunabula', '0014_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='fullName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
