# Generated by Django 3.2.20 on 2024-09-26 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incunabula', '0015_alter_person_fullname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OfficePerson',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
