# Generated by Django 3.2.20 on 2024-09-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incunabula', '0016_auto_20240926_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
