# Generated by Django 3.2.20 on 2024-10-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incunabula', '0017_book_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
    ]
