# Generated by Django 3.2.20 on 2024-10-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incunabula', '0018_alter_book_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='_id',
            field=models.CharField(default=10, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
