# Generated by Django 3.2.20 on 2024-10-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incunabula', '0019_auto_20241003_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='_id',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
