# Generated by Django 3.2.20 on 2024-10-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incunabula', '0020_alter_book__id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='_id',
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
    ]
