# Generated by Django 3.2.20 on 2024-10-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incunabula', '0021_auto_20241003_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
